[2025-02-05T00:30:36.003+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T00:30:36.014+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.ad_hoc_rnk_amount_run manual__2025-02-05T00:00:00+00:00 [queued]>
[2025-02-05T00:30:36.021+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.ad_hoc_rnk_amount_run manual__2025-02-05T00:00:00+00:00 [queued]>
[2025-02-05T00:30:36.022+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-02-05T00:30:36.033+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.ad_hoc_rnk_amount_run> on 2025-02-05 00:00:00+00:00
[2025-02-05T00:30:36.037+0000] {standard_task_runner.py:63} INFO - Started process 1817 to run task
[2025-02-05T00:30:36.040+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.ad_hoc_rnk_amount_run', 'manual__2025-02-05T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmpzxpow9lx']
[2025-02-05T00:30:36.042+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask model_credit_fraud.ad_hoc_rnk_amount_run
[2025-02-05T00:30:36.083+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.ad_hoc_rnk_amount_run manual__2025-02-05T00:00:00+00:00 [running]> on host eb20c43aeeb4
[2025-02-05T00:30:36.169+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.ad_hoc_rnk_amount_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T00:00:00+00:00'
[2025-02-05T00:30:36.172+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T00:30:38.163+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T00:30:38.164+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmprhe2zcae from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T00:30:38.173+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-05T00:30:38.178+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T00:30:38.188+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T00:30:38.190+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-05T00:30:38.191+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'ad_hoc_rnk_amount', '--project-dir', '/tmp/tmprhe2zcae', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmprhe2zcae
[2025-02-05T00:30:38.211+0000] {logging_mixin.py:188} INFO - 00:30:38  Running with dbt=1.6.1
[2025-02-05T00:30:38.323+0000] {logging_mixin.py:188} INFO - 00:30:38  Registered adapter: postgres=1.6.1
[2025-02-05T00:30:38.582+0000] {logging_mixin.py:188} INFO - 00:30:38  Found 3 models, 1 snapshot, 5 tests, 1 source, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T00:30:38.584+0000] {logging_mixin.py:188} INFO - 00:30:38
[2025-02-05T00:30:38.629+0000] {logging_mixin.py:188} INFO - 00:30:38  Concurrency: 1 threads (target='prod')
[2025-02-05T00:30:38.630+0000] {logging_mixin.py:188} INFO - 00:30:38
[2025-02-05T00:30:38.634+0000] {logging_mixin.py:188} INFO - 00:30:38  1 of 1 START sql table model dm_credit_operations.ad_hoc_rnk_amount ............ [RUN]
[2025-02-05T00:30:47.440+0000] {logging_mixin.py:188} INFO - 00:30:47  1 of 1 OK created sql table model dm_credit_operations.ad_hoc_rnk_amount ....... [SELECT 3 in 8.80s]
[2025-02-05T00:30:47.450+0000] {logging_mixin.py:188} INFO - 00:30:47
[2025-02-05T00:30:47.452+0000] {logging_mixin.py:188} INFO - 00:30:47  Finished running 1 table model in 0 hours 0 minutes and 8.87 seconds (8.87s).
[2025-02-05T00:30:47.459+0000] {logging_mixin.py:188} INFO - 00:30:47
[2025-02-05T00:30:47.460+0000] {logging_mixin.py:188} INFO - 00:30:47  Completed successfully
[2025-02-05T00:30:47.461+0000] {logging_mixin.py:188} INFO - 00:30:47
[2025-02-05T00:30:47.462+0000] {logging_mixin.py:188} INFO - 00:30:47  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T00:30:48.226+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T00:30:48.267+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-05T00:30:48.268+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.ad_hoc_rnk_amount', extra=None)]
[2025-02-05T00:30:48.269+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T00:30:48.270+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T00:30:48.286+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-05T00:30:48.324+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T00:30:48.367+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.ad_hoc_rnk_amount_run, run_id=manual__2025-02-05T00:00:00+00:00, execution_date=20250205T000000, start_date=20250205T003036, end_date=20250205T003048
[2025-02-05T00:30:48.427+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T00:30:48.452+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T00:30:48.456+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
