[2025-02-05T00:32:21.757+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T00:32:21.772+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T00:32:21.778+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T00:32:21.779+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T00:32:21.789+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.agg_locations_risk_score_run> on 2025-02-04 00:00:00+00:00
[2025-02-05T00:32:21.793+0000] {standard_task_runner.py:63} INFO - Started process 1989 to run task
[2025-02-05T00:32:21.795+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.agg_locations_risk_score_run', 'manual__2025-02-04T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmp9z5512gy']
[2025-02-05T00:32:21.796+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask model_credit_fraud.agg_locations_risk_score_run
[2025-02-05T00:32:21.835+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [running]> on host eb20c43aeeb4
[2025-02-05T00:32:21.904+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.agg_locations_risk_score_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T00:00:00+00:00'
[2025-02-05T00:32:21.906+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T00:32:24.062+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T00:32:24.064+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpxjmq_x3y from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T00:32:24.070+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-05T00:32:24.074+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T00:32:24.082+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T00:32:24.084+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-05T00:32:24.085+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'agg_locations_risk_score', '--project-dir', '/tmp/tmpxjmq_x3y', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmpxjmq_x3y
[2025-02-05T00:32:24.101+0000] {logging_mixin.py:188} INFO - 00:32:24  Running with dbt=1.6.1
[2025-02-05T00:32:24.193+0000] {logging_mixin.py:188} INFO - 00:32:24  Registered adapter: postgres=1.6.1
[2025-02-05T00:32:24.453+0000] {logging_mixin.py:188} INFO - 00:32:24  Found 3 models, 1 snapshot, 5 tests, 1 source, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T00:32:24.456+0000] {logging_mixin.py:188} INFO - 00:32:24
[2025-02-05T00:32:24.507+0000] {logging_mixin.py:188} INFO - 00:32:24  Concurrency: 1 threads (target='prod')
[2025-02-05T00:32:24.509+0000] {logging_mixin.py:188} INFO - 00:32:24
[2025-02-05T00:32:24.512+0000] {logging_mixin.py:188} INFO - 00:32:24  1 of 1 START sql table model dm_credit_operations.agg_locations_risk_score ..... [RUN]
[2025-02-05T00:32:28.883+0000] {logging_mixin.py:188} INFO - 00:32:28  1 of 1 OK created sql table model dm_credit_operations.agg_locations_risk_score  [SELECT 5 in 4.37s]
[2025-02-05T00:32:28.899+0000] {logging_mixin.py:188} INFO - 00:32:28
[2025-02-05T00:32:28.900+0000] {logging_mixin.py:188} INFO - 00:32:28  Finished running 1 table model in 0 hours 0 minutes and 4.44 seconds (4.44s).
[2025-02-05T00:32:28.910+0000] {logging_mixin.py:188} INFO - 00:32:28
[2025-02-05T00:32:28.912+0000] {logging_mixin.py:188} INFO - 00:32:28  Completed successfully
[2025-02-05T00:32:28.913+0000] {logging_mixin.py:188} INFO - 00:32:28
[2025-02-05T00:32:28.914+0000] {logging_mixin.py:188} INFO - 00:32:28  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T00:32:29.657+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T00:32:29.683+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-05T00:32:29.685+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.agg_locations_risk_score', extra=None)]
[2025-02-05T00:32:29.686+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T00:32:29.686+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T00:32:29.698+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-05T00:32:29.723+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T00:32:29.747+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.agg_locations_risk_score_run, run_id=manual__2025-02-04T00:00:00+00:00, execution_date=20250204T000000, start_date=20250205T003221, end_date=20250205T003229
[2025-02-05T00:32:29.778+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T00:32:29.799+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T00:32:29.802+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-05T01:55:36.125+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T01:55:36.140+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T01:55:36.149+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T01:55:36.150+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T01:55:36.161+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.agg_locations_risk_score_run> on 2025-02-04 00:00:00+00:00
[2025-02-05T01:55:36.166+0000] {standard_task_runner.py:63} INFO - Started process 189 to run task
[2025-02-05T01:55:36.169+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.agg_locations_risk_score_run', 'manual__2025-02-04T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmpqvfqwnqd']
[2025-02-05T01:55:36.171+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask model_credit_fraud.agg_locations_risk_score_run
[2025-02-05T01:55:36.223+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [running]> on host e647bfd7b2d2
[2025-02-05T01:55:36.308+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.agg_locations_risk_score_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T00:00:00+00:00'
[2025-02-05T01:55:36.311+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T01:55:38.678+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T01:55:38.679+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmp5p8iy2ad from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T01:55:38.685+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-05T01:55:38.691+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T01:55:38.700+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T01:55:38.702+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-05T01:55:38.703+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'agg_locations_risk_score', '--project-dir', '/tmp/tmp5p8iy2ad', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmp5p8iy2ad
[2025-02-05T01:55:38.719+0000] {logging_mixin.py:188} INFO - 01:55:38  Running with dbt=1.6.1
[2025-02-05T01:55:38.827+0000] {logging_mixin.py:188} INFO - 01:55:38  Registered adapter: postgres=1.6.1
[2025-02-05T01:55:39.208+0000] {logging_mixin.py:188} INFO - 01:55:39  Found 3 models, 1 snapshot, 5 tests, 1 source, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T01:55:39.210+0000] {logging_mixin.py:188} INFO - 01:55:39
[2025-02-05T01:55:39.274+0000] {logging_mixin.py:188} INFO - 01:55:39  Concurrency: 1 threads (target='prod')
[2025-02-05T01:55:39.275+0000] {logging_mixin.py:188} INFO - 01:55:39
[2025-02-05T01:55:39.278+0000] {logging_mixin.py:188} INFO - 01:55:39  1 of 1 START sql table model dm_credit_operations.agg_locations_risk_score ..... [RUN]
[2025-02-05T01:55:43.325+0000] {logging_mixin.py:188} INFO - 01:55:43  1 of 1 OK created sql table model dm_credit_operations.agg_locations_risk_score  [SELECT 5 in 4.04s]
[2025-02-05T01:55:43.336+0000] {logging_mixin.py:188} INFO - 01:55:43
[2025-02-05T01:55:43.337+0000] {logging_mixin.py:188} INFO - 01:55:43  Finished running 1 table model in 0 hours 0 minutes and 4.12 seconds (4.12s).
[2025-02-05T01:55:43.345+0000] {logging_mixin.py:188} INFO - 01:55:43
[2025-02-05T01:55:43.346+0000] {logging_mixin.py:188} INFO - 01:55:43  Completed successfully
[2025-02-05T01:55:43.347+0000] {logging_mixin.py:188} INFO - 01:55:43
[2025-02-05T01:55:43.348+0000] {logging_mixin.py:188} INFO - 01:55:43  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T01:55:46.514+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T01:55:46.559+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-05T01:55:46.560+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.agg_locations_risk_score', extra=None)]
[2025-02-05T01:55:46.560+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T01:55:46.561+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T01:55:46.576+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-05T01:55:46.618+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T01:55:46.648+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.agg_locations_risk_score_run, run_id=manual__2025-02-04T00:00:00+00:00, execution_date=20250204T000000, start_date=20250205T015536, end_date=20250205T015546
[2025-02-05T01:55:46.694+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T01:55:46.724+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T01:55:46.727+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-05T14:06:56.519+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T14:06:56.555+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T14:06:56.575+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T14:06:56.576+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T14:06:56.608+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.agg_locations_risk_score_run> on 2025-02-04 00:00:00+00:00
[2025-02-05T14:06:56.616+0000] {standard_task_runner.py:63} INFO - Started process 4662 to run task
[2025-02-05T14:06:56.622+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.agg_locations_risk_score_run', 'manual__2025-02-04T00:00:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmpknkibyaj']
[2025-02-05T14:06:56.624+0000] {standard_task_runner.py:91} INFO - Job 137: Subtask model_credit_fraud.agg_locations_risk_score_run
[2025-02-05T14:06:56.728+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [running]> on host 98025f4a542d
[2025-02-05T14:06:56.886+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.agg_locations_risk_score_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T00:00:00+00:00'
[2025-02-05T14:06:56.893+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T14:07:01.115+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T14:07:01.116+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmp4tg_ymn9 from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T14:07:01.127+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-05T14:07:01.136+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T14:07:01.148+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T14:07:01.150+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-05T14:07:01.151+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'agg_locations_risk_score', '--project-dir', '/tmp/tmp4tg_ymn9', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmp4tg_ymn9
[2025-02-05T14:07:01.185+0000] {logging_mixin.py:188} INFO - 14:07:01  Running with dbt=1.6.1
[2025-02-05T14:07:01.411+0000] {logging_mixin.py:188} INFO - 14:07:01  Registered adapter: postgres=1.6.1
[2025-02-05T14:07:02.369+0000] {logging_mixin.py:188} INFO - 14:07:02  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T14:07:02.380+0000] {logging_mixin.py:188} INFO - 14:07:02
[2025-02-05T14:07:02.538+0000] {logging_mixin.py:188} INFO - 14:07:02  Concurrency: 1 threads (target='prod')
[2025-02-05T14:07:02.547+0000] {logging_mixin.py:188} INFO - 14:07:02
[2025-02-05T14:07:02.558+0000] {logging_mixin.py:188} INFO - 14:07:02  1 of 1 START sql table model dm_credit_operations.agg_locations_risk_score ..... [RUN]
[2025-02-05T14:07:08.711+0000] {logging_mixin.py:188} INFO - 14:07:08  1 of 1 OK created sql table model dm_credit_operations.agg_locations_risk_score  [SELECT 5 in 6.15s]
[2025-02-05T14:07:08.733+0000] {logging_mixin.py:188} INFO - 14:07:08
[2025-02-05T14:07:08.735+0000] {logging_mixin.py:188} INFO - 14:07:08  Finished running 1 table model in 0 hours 0 minutes and 6.35 seconds (6.35s).
[2025-02-05T14:07:08.749+0000] {logging_mixin.py:188} INFO - 14:07:08
[2025-02-05T14:07:08.751+0000] {logging_mixin.py:188} INFO - 14:07:08  Completed successfully
[2025-02-05T14:07:08.752+0000] {logging_mixin.py:188} INFO - 14:07:08
[2025-02-05T14:07:08.753+0000] {logging_mixin.py:188} INFO - 14:07:08  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T14:07:09.543+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T14:07:09.603+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-05T14:07:09.604+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.agg_locations_risk_score', extra=None)]
[2025-02-05T14:07:09.605+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T14:07:09.606+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T14:07:09.636+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-05T14:07:09.694+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T14:07:09.738+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.agg_locations_risk_score_run, run_id=manual__2025-02-04T00:00:00+00:00, execution_date=20250204T000000, start_date=20250205T140656, end_date=20250205T140709
[2025-02-05T14:07:09.812+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T14:07:09.841+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T14:07:09.844+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-05T14:31:43.020+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T14:31:43.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T14:31:43.053+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T14:31:43.054+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T14:31:43.067+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.agg_locations_risk_score_run> on 2025-02-04 00:00:00+00:00
[2025-02-05T14:31:43.072+0000] {standard_task_runner.py:63} INFO - Started process 253 to run task
[2025-02-05T14:31:43.076+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.agg_locations_risk_score_run', 'manual__2025-02-04T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmploj_l9z8']
[2025-02-05T14:31:43.078+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask model_credit_fraud.agg_locations_risk_score_run
[2025-02-05T14:31:43.135+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [running]> on host eb17fa5f9c23
[2025-02-05T14:31:43.263+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.agg_locations_risk_score_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T00:00:00+00:00'
[2025-02-05T14:31:43.268+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T14:31:46.712+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T14:31:46.714+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpuvglwkoh from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T14:31:46.721+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-05T14:31:46.728+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T14:31:46.738+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T14:31:46.740+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-05T14:31:46.741+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'agg_locations_risk_score', '--project-dir', '/tmp/tmpuvglwkoh', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmpuvglwkoh
[2025-02-05T14:31:46.762+0000] {logging_mixin.py:188} INFO - 14:31:46  Running with dbt=1.6.1
[2025-02-05T14:31:46.903+0000] {logging_mixin.py:188} INFO - 14:31:46  Registered adapter: postgres=1.6.1
[2025-02-05T14:31:47.654+0000] {logging_mixin.py:188} INFO - 14:31:47  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T14:31:47.657+0000] {logging_mixin.py:188} INFO - 14:31:47
[2025-02-05T14:31:47.739+0000] {logging_mixin.py:188} INFO - 14:31:47  Concurrency: 1 threads (target='prod')
[2025-02-05T14:31:47.740+0000] {logging_mixin.py:188} INFO - 14:31:47
[2025-02-05T14:31:47.747+0000] {logging_mixin.py:188} INFO - 14:31:47  1 of 1 START sql table model dm_credit_operations.agg_locations_risk_score ..... [RUN]
[2025-02-05T14:31:47.822+0000] {logging_mixin.py:188} INFO - 14:31:47  1 of 1 ERROR creating sql table model dm_credit_operations.agg_locations_risk_score  [ERROR in 0.07s]
[2025-02-05T14:31:47.840+0000] {logging_mixin.py:188} INFO - 14:31:47
[2025-02-05T14:31:47.841+0000] {logging_mixin.py:188} INFO - 14:31:47  Finished running 1 table model in 0 hours 0 minutes and 0.18 seconds (0.18s).
[2025-02-05T14:31:47.854+0000] {logging_mixin.py:188} INFO - 14:31:47
[2025-02-05T14:31:47.855+0000] {logging_mixin.py:188} INFO - 14:31:47  Completed with 1 error and 0 warnings:
[2025-02-05T14:31:47.856+0000] {logging_mixin.py:188} INFO - 14:31:47
[2025-02-05T14:31:47.858+0000] {logging_mixin.py:188} INFO - 14:31:47  Database Error in model agg_locations_risk_score (models/marts/credit_fraud/agg_locations_risk_score.sql)
[2025-02-05T14:31:47.859+0000] {logging_mixin.py:188} INFO - 14:31:47    relation "dm_credit_operations.stg_credit_fraud" does not exist
[2025-02-05T14:31:47.859+0000] {logging_mixin.py:188} INFO - 14:31:47    LINE 16:  "***"."dm_credit_operations"."stg_credit_fraud"
[2025-02-05T14:31:47.860+0000] {logging_mixin.py:188} INFO - 14:31:47              ^
[2025-02-05T14:31:47.861+0000] {logging_mixin.py:188} INFO - 14:31:47    compiled Code at target/run/***/models/marts/credit_fraud/agg_locations_risk_score.sql
[2025-02-05T14:31:47.863+0000] {logging_mixin.py:188} INFO - 14:31:47
[2025-02-05T14:31:47.864+0000] {logging_mixin.py:188} INFO - 14:31:47  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-02-05T14:31:48.647+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T14:31:48.650+0000] {local.py:494} INFO - Inlets: []
[2025-02-05T14:31:48.651+0000] {local.py:495} INFO - Outlets: []
[2025-02-05T14:31:48.652+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T14:31:48.653+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T14:31:48.669+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-05T14:31:48.711+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T14:31:48.721+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/base.py", line 268, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 654, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 509, in run_command
    self.handle_exception(result)
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 237, in handle_exception_dbt_runner
    raise AirflowException(f"dbt invocation completed with errors: {error_message}")
airflow.exceptions.AirflowException: dbt invocation completed with errors: agg_locations_risk_score: Database Error in model agg_locations_risk_score (models/marts/credit_fraud/agg_locations_risk_score.sql)
  relation "dm_credit_operations.stg_credit_fraud" does not exist
  LINE 16:  "***"."dm_credit_operations"."stg_credit_fraud"
            ^
  compiled Code at target/run/***/models/marts/credit_fraud/agg_locations_risk_score.sql
[2025-02-05T14:31:48.726+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.agg_locations_risk_score_run, run_id=manual__2025-02-04T00:00:00+00:00, execution_date=20250204T000000, start_date=20250205T143143, end_date=20250205T143148
[2025-02-05T14:31:48.738+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task model_credit_fraud.agg_locations_risk_score_run (dbt invocation completed with errors: agg_locations_risk_score: Database Error in model agg_locations_risk_score (models/marts/credit_fraud/agg_locations_risk_score.sql)
  relation "dm_credit_operations.stg_credit_fraud" does not exist
  LINE 16:  "***"."dm_credit_operations"."stg_credit_fraud"
            ^
  compiled Code at target/run/***/models/marts/credit_fraud/agg_locations_risk_score.sql; 253)
[2025-02-05T14:31:48.781+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-05T14:31:48.799+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T14:31:48.802+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-05T14:57:16.968+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T14:57:16.984+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T14:57:16.993+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T14:57:16.994+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T14:57:17.004+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.agg_locations_risk_score_run> on 2025-02-04 00:00:00+00:00
[2025-02-05T14:57:17.009+0000] {standard_task_runner.py:63} INFO - Started process 276 to run task
[2025-02-05T14:57:17.012+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.agg_locations_risk_score_run', 'manual__2025-02-04T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmpmhxy8j4c']
[2025-02-05T14:57:17.013+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask model_credit_fraud.agg_locations_risk_score_run
[2025-02-05T14:57:17.063+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [running]> on host 7c7f80fafcb7
[2025-02-05T14:57:17.135+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.agg_locations_risk_score_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T00:00:00+00:00'
[2025-02-05T14:57:17.138+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T14:57:19.161+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T14:57:19.162+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpq1wdpq7m from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T14:57:19.171+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-05T14:57:19.177+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T14:57:19.185+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T14:57:19.187+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-05T14:57:19.188+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'agg_locations_risk_score', '--project-dir', '/tmp/tmpq1wdpq7m', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmpq1wdpq7m
[2025-02-05T14:57:19.206+0000] {logging_mixin.py:188} INFO - 14:57:19  Running with dbt=1.6.1
[2025-02-05T14:57:19.322+0000] {logging_mixin.py:188} INFO - 14:57:19  Registered adapter: postgres=1.6.1
[2025-02-05T14:57:19.912+0000] {logging_mixin.py:188} INFO - 14:57:19  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T14:57:19.914+0000] {logging_mixin.py:188} INFO - 14:57:19
[2025-02-05T14:57:19.972+0000] {logging_mixin.py:188} INFO - 14:57:19  Concurrency: 1 threads (target='prod')
[2025-02-05T14:57:19.973+0000] {logging_mixin.py:188} INFO - 14:57:19
[2025-02-05T14:57:19.977+0000] {logging_mixin.py:188} INFO - 14:57:19  1 of 1 START sql table model dm_credit_operations.agg_locations_risk_score ..... [RUN]
[2025-02-05T14:57:23.899+0000] {logging_mixin.py:188} INFO - 14:57:23  1 of 1 OK created sql table model dm_credit_operations.agg_locations_risk_score  [SELECT 5 in 3.92s]
[2025-02-05T14:57:23.916+0000] {logging_mixin.py:188} INFO - 14:57:23
[2025-02-05T14:57:23.918+0000] {logging_mixin.py:188} INFO - 14:57:23  Finished running 1 table model in 0 hours 0 minutes and 4.00 seconds (4.00s).
[2025-02-05T14:57:23.939+0000] {logging_mixin.py:188} INFO - 14:57:23
[2025-02-05T14:57:23.940+0000] {logging_mixin.py:188} INFO - 14:57:23  Completed successfully
[2025-02-05T14:57:23.941+0000] {logging_mixin.py:188} INFO - 14:57:23
[2025-02-05T14:57:23.942+0000] {logging_mixin.py:188} INFO - 14:57:23  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T14:57:24.696+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T14:57:24.738+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-05T14:57:24.739+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.agg_locations_risk_score', extra=None)]
[2025-02-05T14:57:24.739+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T14:57:24.740+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T14:57:24.753+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-05T14:57:24.781+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T14:57:24.813+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.agg_locations_risk_score_run, run_id=manual__2025-02-04T00:00:00+00:00, execution_date=20250204T000000, start_date=20250205T145716, end_date=20250205T145724
[2025-02-05T14:57:24.848+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T14:57:24.866+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T14:57:24.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-05T15:08:54.621+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T15:08:54.640+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T15:08:54.649+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T15:08:54.650+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T15:08:54.664+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.agg_locations_risk_score_run> on 2025-02-04 00:00:00+00:00
[2025-02-05T15:08:54.670+0000] {standard_task_runner.py:63} INFO - Started process 276 to run task
[2025-02-05T15:08:54.673+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.agg_locations_risk_score_run', 'manual__2025-02-04T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmphhyeko7t']
[2025-02-05T15:08:54.675+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask model_credit_fraud.agg_locations_risk_score_run
[2025-02-05T15:08:54.725+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [running]> on host 5c897c3a2254
[2025-02-05T15:08:54.800+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.agg_locations_risk_score_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T00:00:00+00:00'
[2025-02-05T15:08:54.803+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T15:08:57.000+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T15:08:57.002+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpe4ckimk0 from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T15:08:57.009+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-05T15:08:57.015+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T15:08:57.023+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T15:08:57.025+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-05T15:08:57.026+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'agg_locations_risk_score', '--project-dir', '/tmp/tmpe4ckimk0', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmpe4ckimk0
[2025-02-05T15:08:57.045+0000] {logging_mixin.py:188} INFO - 15:08:57  Running with dbt=1.6.1
[2025-02-05T15:08:57.158+0000] {logging_mixin.py:188} INFO - 15:08:57  Registered adapter: postgres=1.6.1
[2025-02-05T15:08:57.755+0000] {logging_mixin.py:188} INFO - 15:08:57  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T15:08:57.758+0000] {logging_mixin.py:188} INFO - 15:08:57
[2025-02-05T15:08:57.816+0000] {logging_mixin.py:188} INFO - 15:08:57  Concurrency: 1 threads (target='prod')
[2025-02-05T15:08:57.817+0000] {logging_mixin.py:188} INFO - 15:08:57
[2025-02-05T15:08:57.821+0000] {logging_mixin.py:188} INFO - 15:08:57  1 of 1 START sql table model dm_credit_operations.agg_locations_risk_score ..... [RUN]
[2025-02-05T15:09:00.188+0000] {logging_mixin.py:188} INFO - 15:09:00  1 of 1 OK created sql table model dm_credit_operations.agg_locations_risk_score  [SELECT 5 in 2.37s]
[2025-02-05T15:09:00.204+0000] {logging_mixin.py:188} INFO - 15:09:00
[2025-02-05T15:09:00.205+0000] {logging_mixin.py:188} INFO - 15:09:00  Finished running 1 table model in 0 hours 0 minutes and 2.44 seconds (2.44s).
[2025-02-05T15:09:00.215+0000] {logging_mixin.py:188} INFO - 15:09:00
[2025-02-05T15:09:00.216+0000] {logging_mixin.py:188} INFO - 15:09:00  Completed successfully
[2025-02-05T15:09:00.217+0000] {logging_mixin.py:188} INFO - 15:09:00
[2025-02-05T15:09:00.219+0000] {logging_mixin.py:188} INFO - 15:09:00  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T15:09:00.996+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T15:09:01.030+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-05T15:09:01.031+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.agg_locations_risk_score', extra=None)]
[2025-02-05T15:09:01.031+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T15:09:01.032+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T15:09:01.043+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-05T15:09:01.079+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T15:09:01.103+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.agg_locations_risk_score_run, run_id=manual__2025-02-04T00:00:00+00:00, execution_date=20250204T000000, start_date=20250205T150854, end_date=20250205T150901
[2025-02-05T15:09:01.142+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T15:09:01.159+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T15:09:01.161+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-05T16:47:02.394+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T16:47:02.409+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T16:47:02.418+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T16:47:02.419+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T16:47:02.427+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.agg_locations_risk_score_run> on 2025-02-04 00:00:00+00:00
[2025-02-05T16:47:02.432+0000] {standard_task_runner.py:63} INFO - Started process 296 to run task
[2025-02-05T16:47:02.434+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.agg_locations_risk_score_run', 'manual__2025-02-04T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmp9jsd9cvl']
[2025-02-05T16:47:02.436+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask model_credit_fraud.agg_locations_risk_score_run
[2025-02-05T16:47:02.479+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T00:00:00+00:00 [running]> on host 584eb3626689
[2025-02-05T16:47:02.545+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.agg_locations_risk_score_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T00:00:00+00:00'
[2025-02-05T16:47:02.548+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T16:47:05.327+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T16:47:05.328+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpd4a6jvba from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T16:47:05.339+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-05T16:47:05.346+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T16:47:05.355+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T16:47:05.357+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-05T16:47:05.358+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'agg_locations_risk_score', '--project-dir', '/tmp/tmpd4a6jvba', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmpd4a6jvba
[2025-02-05T16:47:05.378+0000] {logging_mixin.py:188} INFO - 16:47:05  Running with dbt=1.6.1
[2025-02-05T16:47:05.561+0000] {logging_mixin.py:188} INFO - 16:47:05  Registered adapter: postgres=1.6.1
[2025-02-05T16:47:06.265+0000] {logging_mixin.py:188} INFO - 16:47:06  Found 5 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T16:47:06.268+0000] {logging_mixin.py:188} INFO - 16:47:06
[2025-02-05T16:47:06.332+0000] {logging_mixin.py:188} INFO - 16:47:06  Concurrency: 1 threads (target='prod')
[2025-02-05T16:47:06.333+0000] {logging_mixin.py:188} INFO - 16:47:06
[2025-02-05T16:47:06.337+0000] {logging_mixin.py:188} INFO - 16:47:06  1 of 1 START sql table model dm_credit_operations.agg_locations_risk_score ..... [RUN]
[2025-02-05T16:47:10.367+0000] {logging_mixin.py:188} INFO - 16:47:10  1 of 1 OK created sql table model dm_credit_operations.agg_locations_risk_score  [SELECT 5 in 4.03s]
[2025-02-05T16:47:10.383+0000] {logging_mixin.py:188} INFO - 16:47:10
[2025-02-05T16:47:10.384+0000] {logging_mixin.py:188} INFO - 16:47:10  Finished running 1 table model in 0 hours 0 minutes and 4.11 seconds (4.11s).
[2025-02-05T16:47:10.395+0000] {logging_mixin.py:188} INFO - 16:47:10
[2025-02-05T16:47:10.396+0000] {logging_mixin.py:188} INFO - 16:47:10  Completed successfully
[2025-02-05T16:47:10.397+0000] {logging_mixin.py:188} INFO - 16:47:10
[2025-02-05T16:47:10.398+0000] {logging_mixin.py:188} INFO - 16:47:10  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T16:47:11.168+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T16:47:11.206+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-05T16:47:11.207+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.agg_locations_risk_score', extra=None)]
[2025-02-05T16:47:11.207+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T16:47:11.208+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T16:47:11.220+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-05T16:47:11.255+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T16:47:11.282+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.agg_locations_risk_score_run, run_id=manual__2025-02-04T00:00:00+00:00, execution_date=20250204T000000, start_date=20250205T164702, end_date=20250205T164711
[2025-02-05T16:47:11.341+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T16:47:11.360+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T16:47:11.362+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
