[2025-02-05T13:41:06.005+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T13:41:06.025+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [queued]>
[2025-02-05T13:41:06.033+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [queued]>
[2025-02-05T13:41:06.034+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T13:41:06.046+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): model_sales.localiza_dw_test> on 2025-02-04 04:00:00+00:00
[2025-02-05T13:41:06.051+0000] {standard_task_runner.py:63} INFO - Started process 4415 to run task
[2025-02-05T13:41:06.054+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_sales', 'model_sales.localiza_dw_test', 'scheduled__2025-02-04T04:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_sales.py', '--cfg-path', '/tmp/tmps7hcgc60']
[2025-02-05T13:41:06.056+0000] {standard_task_runner.py:91} INFO - Job 131: Subtask model_sales.localiza_dw_test
[2025-02-05T13:41:06.109+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [running]> on host 98025f4a542d
[2025-02-05T13:41:06.193+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_sales' AIRFLOW_CTX_TASK_ID='model_sales.localiza_dw_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-04T04:00:00+00:00'
[2025-02-05T13:41:06.195+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T13:41:07.076+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T13:41:07.078+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpbnbwt6q0 from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T13:41:07.088+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_sales__model_sales/target/partial_parse.msgpack
[2025-02-05T13:41:07.095+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T13:41:07.106+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T13:41:07.107+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf/profiles.yml.
[2025-02-05T13:41:07.108+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['test', '--select', 'path:seeds path:models/marts/sales', '--vars', '{"PROD": P003,                                 "LIMITE_QUANTIDADE": 500,                                 "DATA_INICIO": 1999-01-01,                                 "DATA_FIM": 2025-02-05}', '--project-dir', '/tmp/tmpbnbwt6q0', '--profiles-dir', '/tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf', '--profile', '***', '--target', 'prod']
 in /tmp/tmpbnbwt6q0
[2025-02-05T13:41:07.131+0000] {logging_mixin.py:188} INFO - 13:41:07  Running with dbt=1.6.1
[2025-02-05T13:41:07.249+0000] {logging_mixin.py:188} INFO - 13:41:07  Registered adapter: postgres=1.6.1
[2025-02-05T13:41:07.917+0000] {logging_mixin.py:188} INFO - 13:41:07  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T13:41:07.938+0000] {logging_mixin.py:188} INFO - 13:41:07
[2025-02-05T13:41:07.940+0000] {logging_mixin.py:188} INFO - 13:41:07  Nothing to do. Try checking your model configs and model specification args
[2025-02-05T13:41:08.718+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T13:41:08.722+0000] {local.py:494} INFO - Inlets: []
[2025-02-05T13:41:08.723+0000] {local.py:495} INFO - Outlets: []
[2025-02-05T13:41:08.724+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T13:41:08.725+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T13:41:08.755+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_sales to 2025-02-05 04:00:00+00:00, run_after=2025-02-06 04:00:00+00:00
[2025-02-05T13:41:08.800+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T13:41:08.814+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_sales, task_id=model_sales.***_test, run_id=scheduled__2025-02-04T04:00:00+00:00, execution_date=20250204T040000, start_date=20250205T134106, end_date=20250205T134108
[2025-02-05T13:41:08.874+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T13:41:08.897+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T13:41:08.900+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-05T14:31:21.119+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T14:31:21.141+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [queued]>
[2025-02-05T14:31:21.153+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [queued]>
[2025-02-05T14:31:21.154+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T14:31:21.169+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): model_sales.localiza_dw_test> on 2025-02-04 04:00:00+00:00
[2025-02-05T14:31:21.175+0000] {standard_task_runner.py:63} INFO - Started process 207 to run task
[2025-02-05T14:31:21.179+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_sales', 'model_sales.localiza_dw_test', 'scheduled__2025-02-04T04:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_sales.py', '--cfg-path', '/tmp/tmpcg26oq0v']
[2025-02-05T14:31:21.180+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask model_sales.localiza_dw_test
[2025-02-05T14:31:21.250+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [running]> on host eb17fa5f9c23
[2025-02-05T14:31:21.356+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_sales' AIRFLOW_CTX_TASK_ID='model_sales.localiza_dw_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-04T04:00:00+00:00'
[2025-02-05T14:31:21.360+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T14:31:24.365+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T14:31:24.368+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpe74ekr_x from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T14:31:24.378+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_sales__model_sales/target/partial_parse.msgpack
[2025-02-05T14:31:24.385+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T14:31:24.398+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T14:31:24.400+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf/profiles.yml.
[2025-02-05T14:31:24.401+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['test', '--select', 'path:seeds path:models/marts/sales', '--vars', '{"PROD": P003,                                 "LIMITE_QUANTIDADE": 500,                                 "DATA_INICIO": 1999-01-01,                                 "DATA_FIM": 2025-02-05}', '--project-dir', '/tmp/tmpe74ekr_x', '--profiles-dir', '/tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf', '--profile', '***', '--target', 'prod']
 in /tmp/tmpe74ekr_x
[2025-02-05T14:31:24.425+0000] {logging_mixin.py:188} INFO - 14:31:24  Running with dbt=1.6.1
[2025-02-05T14:31:24.584+0000] {logging_mixin.py:188} INFO - 14:31:24  Registered adapter: postgres=1.6.1
[2025-02-05T14:31:25.681+0000] {logging_mixin.py:188} INFO - 14:31:25  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T14:31:25.706+0000] {logging_mixin.py:188} INFO - 14:31:25
[2025-02-05T14:31:25.708+0000] {logging_mixin.py:188} INFO - 14:31:25  Nothing to do. Try checking your model configs and model specification args
[2025-02-05T14:31:26.534+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T14:31:26.539+0000] {local.py:494} INFO - Inlets: []
[2025-02-05T14:31:26.540+0000] {local.py:495} INFO - Outlets: []
[2025-02-05T14:31:26.542+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T14:31:26.543+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T14:31:26.574+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_sales to 2025-02-05 04:00:00+00:00, run_after=2025-02-06 04:00:00+00:00
[2025-02-05T14:31:26.612+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T14:31:26.630+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_sales, task_id=model_sales.***_test, run_id=scheduled__2025-02-04T04:00:00+00:00, execution_date=20250204T040000, start_date=20250205T143121, end_date=20250205T143126
[2025-02-05T14:31:26.691+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T14:31:26.712+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T14:31:26.716+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-05T14:56:42.095+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T14:56:42.113+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [queued]>
[2025-02-05T14:56:42.122+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [queued]>
[2025-02-05T14:56:42.122+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T14:56:42.133+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): model_sales.localiza_dw_test> on 2025-02-04 04:00:00+00:00
[2025-02-05T14:56:42.138+0000] {standard_task_runner.py:63} INFO - Started process 204 to run task
[2025-02-05T14:56:42.141+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_sales', 'model_sales.localiza_dw_test', 'scheduled__2025-02-04T04:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_sales.py', '--cfg-path', '/tmp/tmp0szp9lk1']
[2025-02-05T14:56:42.142+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask model_sales.localiza_dw_test
[2025-02-05T14:56:42.195+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [running]> on host 7c7f80fafcb7
[2025-02-05T14:56:42.275+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_sales' AIRFLOW_CTX_TASK_ID='model_sales.localiza_dw_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-04T04:00:00+00:00'
[2025-02-05T14:56:42.277+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T14:56:44.661+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T14:56:44.663+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpg9y1zjv1 from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T14:56:44.674+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_sales__model_sales/target/partial_parse.msgpack
[2025-02-05T14:56:44.680+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T14:56:44.688+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T14:56:44.690+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf/profiles.yml.
[2025-02-05T14:56:44.691+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['test', '--select', 'path:seeds path:models/marts/sales', '--vars', '{"PROD": P003,                                 "LIMITE_QUANTIDADE": 500,                                 "DATA_INICIO": 1999-01-01,                                 "DATA_FIM": 2025-02-05}', '--project-dir', '/tmp/tmpg9y1zjv1', '--profiles-dir', '/tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf', '--profile', '***', '--target', 'prod']
 in /tmp/tmpg9y1zjv1
[2025-02-05T14:56:44.711+0000] {logging_mixin.py:188} INFO - 14:56:44  Running with dbt=1.6.1
[2025-02-05T14:56:44.824+0000] {logging_mixin.py:188} INFO - 14:56:44  Registered adapter: postgres=1.6.1
[2025-02-05T14:56:45.360+0000] {logging_mixin.py:188} INFO - 14:56:45  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T14:56:45.374+0000] {logging_mixin.py:188} INFO - 14:56:45
[2025-02-05T14:56:45.375+0000] {logging_mixin.py:188} INFO - 14:56:45  Nothing to do. Try checking your model configs and model specification args
[2025-02-05T14:56:46.219+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T14:56:46.221+0000] {local.py:494} INFO - Inlets: []
[2025-02-05T14:56:46.222+0000] {local.py:495} INFO - Outlets: []
[2025-02-05T14:56:46.222+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T14:56:46.223+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T14:56:46.239+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_sales to 2025-02-05 04:00:00+00:00, run_after=2025-02-06 04:00:00+00:00
[2025-02-05T14:56:46.266+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T14:56:46.273+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_sales, task_id=model_sales.***_test, run_id=scheduled__2025-02-04T04:00:00+00:00, execution_date=20250204T040000, start_date=20250205T145642, end_date=20250205T145646
[2025-02-05T14:56:46.309+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T14:56:46.322+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T14:56:46.324+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-05T15:08:18.286+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T15:08:18.301+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [queued]>
[2025-02-05T15:08:18.310+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [queued]>
[2025-02-05T15:08:18.311+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T15:08:18.322+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): model_sales.localiza_dw_test> on 2025-02-04 04:00:00+00:00
[2025-02-05T15:08:18.328+0000] {standard_task_runner.py:63} INFO - Started process 207 to run task
[2025-02-05T15:08:18.331+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_sales', 'model_sales.localiza_dw_test', 'scheduled__2025-02-04T04:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_sales.py', '--cfg-path', '/tmp/tmpkpd3lt97']
[2025-02-05T15:08:18.332+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask model_sales.localiza_dw_test
[2025-02-05T15:08:18.383+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [running]> on host 5c897c3a2254
[2025-02-05T15:08:18.460+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_sales' AIRFLOW_CTX_TASK_ID='model_sales.localiza_dw_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-04T04:00:00+00:00'
[2025-02-05T15:08:18.462+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T15:08:20.887+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T15:08:20.889+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpj8fgajv7 from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T15:08:20.895+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_sales__model_sales/target/partial_parse.msgpack
[2025-02-05T15:08:20.903+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T15:08:20.916+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T15:08:20.918+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf/profiles.yml.
[2025-02-05T15:08:20.919+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['test', '--select', 'path:seeds path:models/marts/sales', '--vars', '{"PROD": "P003", "LIMITE_QUANTIDADE": "500", "DATA_INICIO": "1999-01-01", "DATA_FIM": "2025-02-05"}', '--project-dir', '/tmp/tmpj8fgajv7', '--profiles-dir', '/tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf', '--profile', '***', '--target', 'prod']
 in /tmp/tmpj8fgajv7
[2025-02-05T15:08:20.942+0000] {logging_mixin.py:188} INFO - 15:08:20  Running with dbt=1.6.1
[2025-02-05T15:08:21.092+0000] {logging_mixin.py:188} INFO - 15:08:21  Registered adapter: postgres=1.6.1
[2025-02-05T15:08:21.564+0000] {logging_mixin.py:188} INFO - 15:08:21  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T15:08:21.575+0000] {logging_mixin.py:188} INFO - 15:08:21
[2025-02-05T15:08:21.576+0000] {logging_mixin.py:188} INFO - 15:08:21  Nothing to do. Try checking your model configs and model specification args
[2025-02-05T15:08:22.346+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T15:08:22.348+0000] {local.py:494} INFO - Inlets: []
[2025-02-05T15:08:22.349+0000] {local.py:495} INFO - Outlets: []
[2025-02-05T15:08:22.349+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T15:08:22.350+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T15:08:22.369+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_sales to 2025-02-05 04:00:00+00:00, run_after=2025-02-06 04:00:00+00:00
[2025-02-05T15:08:22.390+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T15:08:22.399+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_sales, task_id=model_sales.***_test, run_id=scheduled__2025-02-04T04:00:00+00:00, execution_date=20250204T040000, start_date=20250205T150818, end_date=20250205T150822
[2025-02-05T15:08:22.421+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T15:08:22.435+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T15:08:22.437+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-05T16:46:26.044+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T16:46:26.058+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [queued]>
[2025-02-05T16:46:26.066+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [queued]>
[2025-02-05T16:46:26.067+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T16:46:26.077+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): model_sales.localiza_dw_test> on 2025-02-04 04:00:00+00:00
[2025-02-05T16:46:26.081+0000] {standard_task_runner.py:63} INFO - Started process 227 to run task
[2025-02-05T16:46:26.084+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_sales', 'model_sales.localiza_dw_test', 'scheduled__2025-02-04T04:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_sales.py', '--cfg-path', '/tmp/tmpunzpomv1']
[2025-02-05T16:46:26.086+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask model_sales.localiza_dw_test
[2025-02-05T16:46:26.134+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_sales.model_sales.localiza_dw_test scheduled__2025-02-04T04:00:00+00:00 [running]> on host 584eb3626689
[2025-02-05T16:46:26.206+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_sales' AIRFLOW_CTX_TASK_ID='model_sales.localiza_dw_test' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-04T04:00:00+00:00'
[2025-02-05T16:46:26.208+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T16:46:28.648+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T16:46:28.649+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmp3rtfsayq from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T16:46:28.658+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_sales__model_sales/target/partial_parse.msgpack
[2025-02-05T16:46:28.665+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T16:46:28.675+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T16:46:28.677+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf/profiles.yml.
[2025-02-05T16:46:28.677+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['test', '--select', 'path:seeds path:models/marts/sales', '--vars', '{"PROD": "P003", "LIMITE_QUANTIDADE": "500", "DATA_INICIO": "1999-01-01", "DATA_FIM": "2025-02-05"}', '--project-dir', '/tmp/tmp3rtfsayq', '--profiles-dir', '/tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf', '--profile', '***', '--target', 'prod']
 in /tmp/tmp3rtfsayq
[2025-02-05T16:46:28.702+0000] {logging_mixin.py:188} INFO - 16:46:28  Running with dbt=1.6.1
[2025-02-05T16:46:28.816+0000] {logging_mixin.py:188} INFO - 16:46:28  Registered adapter: postgres=1.6.1
[2025-02-05T16:46:29.505+0000] {logging_mixin.py:188} INFO - 16:46:29  Found 5 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T16:46:29.520+0000] {logging_mixin.py:188} INFO - 16:46:29
[2025-02-05T16:46:29.522+0000] {logging_mixin.py:188} INFO - 16:46:29  Nothing to do. Try checking your model configs and model specification args
[2025-02-05T16:46:30.276+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T16:46:30.278+0000] {local.py:494} INFO - Inlets: []
[2025-02-05T16:46:30.279+0000] {local.py:495} INFO - Outlets: []
[2025-02-05T16:46:30.279+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T16:46:30.279+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T16:46:30.297+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_sales to 2025-02-05 04:00:00+00:00, run_after=2025-02-06 04:00:00+00:00
[2025-02-05T16:46:30.321+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T16:46:30.328+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_sales, task_id=model_sales.***_test, run_id=scheduled__2025-02-04T04:00:00+00:00, execution_date=20250204T040000, start_date=20250205T164626, end_date=20250205T164630
[2025-02-05T16:46:30.369+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T16:46:30.385+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T16:46:30.387+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
