[2025-02-04T22:59:05.061+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-04T22:59:05.072+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.stg_credit_fraud_run manual__2025-02-04T22:52:25.583411+00:00 [queued]>
[2025-02-04T22:59:05.079+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.stg_credit_fraud_run manual__2025-02-04T22:52:25.583411+00:00 [queued]>
[2025-02-04T22:59:05.080+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-02-04T22:59:05.088+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.stg_credit_fraud_run> on 2025-02-04 22:52:25.583411+00:00
[2025-02-04T22:59:05.093+0000] {standard_task_runner.py:63} INFO - Started process 825 to run task
[2025-02-04T22:59:05.095+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.stg_credit_fraud_run', 'manual__2025-02-04T22:52:25.583411+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmp4n6dlbxu']
[2025-02-04T22:59:05.096+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask model_credit_fraud.stg_credit_fraud_run
[2025-02-04T22:59:05.133+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.stg_credit_fraud_run manual__2025-02-04T22:52:25.583411+00:00 [running]> on host eb20c43aeeb4
[2025-02-04T22:59:05.191+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.stg_credit_fraud_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T22:52:25.583411+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T22:52:25.583411+00:00'
[2025-02-04T22:59:05.193+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-04T22:59:06.794+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-04T22:59:06.795+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpak0fuvkt from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-04T22:59:06.800+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-04T22:59:06.803+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-04T22:59:06.810+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-04T22:59:06.811+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-04T22:59:06.812+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stg_credit_fraud', '--project-dir', '/tmp/tmpak0fuvkt', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmpak0fuvkt
[2025-02-04T22:59:06.823+0000] {logging_mixin.py:188} INFO - 22:59:06  Running with dbt=1.6.1
[2025-02-04T22:59:06.911+0000] {logging_mixin.py:188} INFO - 22:59:06  Registered adapter: postgres=1.6.1
[2025-02-04T22:59:06.932+0000] {logging_mixin.py:188} INFO - 22:59:06  Unable to do partial parsing because profile has changed
[2025-02-04T22:59:06.933+0000] {logging_mixin.py:188} INFO - 22:59:06  Unable to do partial parsing because env vars used in profiles.yml have changed
[2025-02-04T22:59:07.640+0000] {logging_mixin.py:188} INFO - 22:59:07  Found 3 models, 1 snapshot, 5 tests, 1 source, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-04T22:59:07.643+0000] {logging_mixin.py:188} INFO - 22:59:07
[2025-02-04T22:59:07.697+0000] {logging_mixin.py:188} INFO - 22:59:07  Concurrency: 1 threads (target='prod')
[2025-02-04T22:59:07.698+0000] {logging_mixin.py:188} INFO - 22:59:07
[2025-02-04T22:59:07.701+0000] {logging_mixin.py:188} INFO - 22:59:07  1 of 1 START sql view model dm_credit_operations.stg_credit_fraud .............. [RUN]
[2025-02-04T22:59:07.770+0000] {logging_mixin.py:188} INFO - 22:59:07  1 of 1 OK created sql view model dm_credit_operations.stg_credit_fraud ......... [CREATE VIEW in 0.07s]
[2025-02-04T22:59:07.779+0000] {logging_mixin.py:188} INFO - 22:59:07
[2025-02-04T22:59:07.780+0000] {logging_mixin.py:188} INFO - 22:59:07  Finished running 1 view model in 0 hours 0 minutes and 0.14 seconds (0.14s).
[2025-02-04T22:59:07.787+0000] {logging_mixin.py:188} INFO - 22:59:07
[2025-02-04T22:59:07.787+0000] {logging_mixin.py:188} INFO - 22:59:07  Completed successfully
[2025-02-04T22:59:07.789+0000] {logging_mixin.py:188} INFO - 22:59:07
[2025-02-04T22:59:07.789+0000] {logging_mixin.py:188} INFO - 22:59:07  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-04T22:59:08.526+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-04T22:59:08.579+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations_stage.raw_credit_fraud', extra=None)]
[2025-02-04T22:59:08.580+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-04T22:59:08.581+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-04T22:59:08.582+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-04T22:59:08.595+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-04T22:59:08.617+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-04T22:59:08.641+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.stg_credit_fraud_run, run_id=manual__2025-02-04T22:52:25.583411+00:00, execution_date=20250204T225225, start_date=20250204T225905, end_date=20250204T225908
[2025-02-04T22:59:08.692+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-04T22:59:08.709+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-04T22:59:08.713+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
